{% set name = "dlib" %}
{% set version = "19.24.2" %}
{% set tag = "v" ~ ".".join(version.split(".")[:2]) %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d4f618073bc6b297aa01ce05595a2d32b5b37e69cafd99f796e77346f6dcfb5

  patches:
    - lapack_sgetrf.patch      # [unix]
    - setup_cmake_args.patch
    - fix_libtools_error.patch  # [osx]
    - unvendor_pybind11.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('dlib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - pkg-config
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - libjpeg-turbo
    - libcblas  # [not win]
    - liblapack   # [not win]
    - libpng
    - numpy
    - pip
    - pybind11
    - python
    - sqlite  # [not win]
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  files:
    - test_data/face.jpg
    - test_data/face.png
    - test_data/images.xml
    # contains test configurations including some skips for missing fixtures
    - setup.cfg
  source_files:
    - tools/python/test
  requires:
    - more-itertools
    - pillow
    - pip
    - pytest>=7
    - pytest-azurepipelines
    - tqdm

  imports:
    - dlib

  commands:
    - python -m pip check
    - python -m pytest tools/python/test

about:
  home: http://dlib.net
  license: BSL-1.0
  license_file: dlib/LICENSE.txt
  summary: toolkit for making real world machine learning and data analysis applications
  dev_url: https://github.com/davisking/dlib
  doc_source_url: https://github.com/davisking/dlib/tree/{{ tag }}/docs
  description: |-
    Dlib is a modern C++ toolkit containing machine learning algorithms and tools
    for creating complex software in C++ to solve real world problems. See
    http://dlib.net for the main project documentation and API reference.

extra:
  recipe-maintainers:
    - patricksnape
    - aldanor
    - Tobias-Fischer
